// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetZoomPoints():Promise<Array<main.ZoomPoint>>;

export function IsRecording():Promise<boolean>;

export function SaveFile(arg1:Array<number>):Promise<void>;

export function StartRecording():Promise<void>;

export function StopRecording():Promise<void>;
