// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableResolutions() {
  return window['go']['main']['App']['GetAvailableResolutions']();
}

export function GetCaptureDevices() {
  return window['go']['main']['App']['GetCaptureDevices']();
}

export function GetResolution() {
  return window['go']['main']['App']['GetResolution']();
}

export function GetResolutionDimensions() {
  return window['go']['main']['App']['GetResolutionDimensions']();
}

export function GetSelectedDevice() {
  return window['go']['main']['App']['GetSelectedDevice']();
}

export function GetZoomPoints() {
  return window['go']['main']['App']['GetZoomPoints']();
}

export function IsRecording() {
  return window['go']['main']['App']['IsRecording']();
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SaveFileWithFPS(arg1, arg2) {
  return window['go']['main']['App']['SaveFileWithFPS'](arg1, arg2);
}

export function SetResolution(arg1) {
  return window['go']['main']['App']['SetResolution'](arg1);
}

export function SetSelectedDevice(arg1) {
  return window['go']['main']['App']['SetSelectedDevice'](arg1);
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}
