// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAvailableResolutions():Promise<Array<string>>;

export function GetCaptureDevices():Promise<Array<main.CaptureDevice>>;

export function GetResolution():Promise<string>;

export function GetResolutionDimensions():Promise<main.ResolutionDimensions>;

export function GetSelectedDevice():Promise<number>;

export function GetZoomPoints():Promise<Array<main.ZoomPoint>>;

export function IsRecording():Promise<boolean>;

export function SaveFile(arg1:Array<number>):Promise<void>;

export function SaveFileWithFPS(arg1:Array<number>,arg2:number):Promise<void>;

export function SetResolution(arg1:string):Promise<void>;

export function SetSelectedDevice(arg1:number):Promise<void>;

export function StartRecording():Promise<void>;

export function StopRecording():Promise<void>;
